// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop/internal/dao/internal"
)

// addressInfoDao is the data access object for the table address_info.
// You can define custom methods on it to extend its functionality as needed.
type addressInfoDao struct {
	*internal.AddressInfoDao
}

var (
	// AddressInfo is a globally accessible object for table address_info operations.
	AddressInfo = addressInfoDao{internal.NewAddressInfoDao()}
)

// Add your custom methods and functionality below.
