// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop/internal/dao/internal"
)

// adminInfoDao is the data access object for the table admin_info.
// You can define custom methods on it to extend its functionality as needed.
type adminInfoDao struct {
	*internal.AdminInfoDao
}

var (
	// AdminInfo is a globally accessible object for table admin_info operations.
	AdminInfo = adminInfoDao{internal.NewAdminInfoDao()}
)

// Add your custom methods and functionality below.
