// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop/internal/dao/internal"
)

// articleInfoDao is the data access object for the table article_info.
// You can define custom methods on it to extend its functionality as needed.
type articleInfoDao struct {
	*internal.ArticleInfoDao
}

var (
	// ArticleInfo is a globally accessible object for table article_info operations.
	ArticleInfo = articleInfoDao{internal.NewArticleInfoDao()}
)

// Add your custom methods and functionality below.
