// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop/internal/dao/internal"
)

// cartInfoDao is the data access object for the table cart_info.
// You can define custom methods on it to extend its functionality as needed.
type cartInfoDao struct {
	*internal.CartInfoDao
}

var (
	// CartInfo is a globally accessible object for table cart_info operations.
	CartInfo = cartInfoDao{internal.NewCartInfoDao()}
)

// Add your custom methods and functionality below.
