// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop/internal/dao/internal"
)

// collectionInfoDao is the data access object for the table collection_info.
// You can define custom methods on it to extend its functionality as needed.
type collectionInfoDao struct {
	*internal.CollectionInfoDao
}

var (
	// CollectionInfo is a globally accessible object for table collection_info operations.
	CollectionInfo = collectionInfoDao{internal.NewCollectionInfoDao()}
)

// Add your custom methods and functionality below.
