// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop/internal/dao/internal"
)

// commentInfoDao is the data access object for the table comment_info.
// You can define custom methods on it to extend its functionality as needed.
type commentInfoDao struct {
	*internal.CommentInfoDao
}

var (
	// CommentInfo is a globally accessible object for table comment_info operations.
	CommentInfo = commentInfoDao{internal.NewCommentInfoDao()}
)

// Add your custom methods and functionality below.
