// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop/internal/dao/internal"
)

// consigneeInfoDao is the data access object for the table consignee_info.
// You can define custom methods on it to extend its functionality as needed.
type consigneeInfoDao struct {
	*internal.ConsigneeInfoDao
}

var (
	// ConsigneeInfo is a globally accessible object for table consignee_info operations.
	ConsigneeInfo = consigneeInfoDao{internal.NewConsigneeInfoDao()}
)

// Add your custom methods and functionality below.
