// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop/internal/dao/internal"
)

// goodsInfoDao is the data access object for the table goods_info.
// You can define custom methods on it to extend its functionality as needed.
type goodsInfoDao struct {
	*internal.GoodsInfoDao
}

var (
	// GoodsInfo is a globally accessible object for table goods_info operations.
	GoodsInfo = goodsInfoDao{internal.NewGoodsInfoDao()}
)

// Add your custom methods and functionality below.
