// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop/internal/dao/internal"
)

// praiseInfoDao is the data access object for the table praise_info.
// You can define custom methods on it to extend its functionality as needed.
type praiseInfoDao struct {
	*internal.PraiseInfoDao
}

var (
	// PraiseInfo is a globally accessible object for table praise_info operations.
	PraiseInfo = praiseInfoDao{internal.NewPraiseInfoDao()}
)

// Add your custom methods and functionality below.
