// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop/internal/dao/internal"
)

// rotationInfoDao is the data access object for the table rotation_info.
// You can define custom methods on it to extend its functionality as needed.
type rotationInfoDao struct {
	*internal.RotationInfoDao
}

var (
	// RotationInfo is a globally accessible object for table rotation_info operations.
	RotationInfo = rotationInfoDao{internal.NewRotationInfoDao()}
)

// Add your custom methods and functionality below.
