// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop/internal/dao/internal"
)

// seckillGoodsDao is the data access object for the table seckill_goods.
// You can define custom methods on it to extend its functionality as needed.
type seckillGoodsDao struct {
	*internal.SeckillGoodsDao
}

var (
	// SeckillGoods is a globally accessible object for table seckill_goods operations.
	SeckillGoods = seckillGoodsDao{internal.NewSeckillGoodsDao()}
)

// Add your custom methods and functionality below.
