// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop/internal/dao/internal"
)

// seckillOrderDao is the data access object for the table seckill_order.
// You can define custom methods on it to extend its functionality as needed.
type seckillOrderDao struct {
	*internal.SeckillOrderDao
}

var (
	// SeckillOrder is a globally accessible object for table seckill_order operations.
	SeckillOrder = seckillOrderDao{internal.NewSeckillOrderDao()}
)

// Add your custom methods and functionality below.
