// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe-shop/internal/dao/internal"
)

// userCouponInfoDao is the data access object for the table user_coupon_info.
// You can define custom methods on it to extend its functionality as needed.
type userCouponInfoDao struct {
	*internal.UserCouponInfoDao
}

var (
	// UserCouponInfo is a globally accessible object for table user_coupon_info operations.
	UserCouponInfo = userCouponInfoDao{internal.NewUserCouponInfoDao()}
)

// Add your custom methods and functionality below.
